Develop a predictive model to determine whether a customer visiting the store will make a purchase or not.Utilized historical customer data (past behavior) as input.Reduce marketing campaign spend by targeting high-potential customers.
Enhance personalized customer experiences.
Improve overall customer satisfaction and loyalty.


**Step-1**
**First we will analyze past purchase behavior dataset**.

**Step-2**
**Feature Engineering**

Then we will perform Feature Engineering to ensure that appropriate data is
selected that should be under stand by a machine learning model. Feature
Engineering is process of selecting and transforming relivent featues or variables in a data set
to improve the machine learning models. This involves for identifing the most
most useful for the model removing irrelivent features and combine excisting features
and normalizing for scaling the features to ensure they have similar scale or
range. The goal of Feature Engineering is to maximize to predict power of the machine
learning model by providing with a relevent and informative Features.

**Step-3**
**Traing a Model**

We will feed the process data into a machine learning algorithm to train a model.Once the Model is
we will tested tested to ensure that it sutable model for our use case.After
that we will use the model to predict with new customers will buy a product or not.
We will also demonstrate how to package the model to predict in anew environment.


Take a data set. This data set has a historical purchage data of some customers. It has some features to analyse the data. It has  purchased feature in that 1 means product purchased and 0 means product  not purchsed. Based on this we will build a model to predict weather a new customer will buy a product or not. First identify the features or variables that can influence the purchased behaviour. Looking at the data set we can confidently say Customer ID and Product Id will not influence the purchase behaviour and feartures deffinetly do.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd .read_csv("https://raw.githubusercontent.com/futurexskill/projects/main/knn-classification/purchase_history.csv")

In [ ]:
df

Customer ID  Gender  Age  Salary Product ID  Price  Purchased
0              1  Female   49   61000        P01   2000          1
1              2    Male   36   30000        P02   2000          1
2              3  Female   26   81000        P02   3500          1
3              4  Female   32   74000        P01   7000          0
4              5  Female   42   56000        P01   5000          0
..           ...     ...  ...     ...        ...    ...        ...
995          996    Male   21   73000        P02   5000          1
996          997    Male   62   54000        P01   5000          0
997          998  Female   41   20000        P03   2000          0
998          999    Male   22   29000        P03   5000          0
999         1000  Female   49   36000        P03   3500          0

[1000 rows x 7 columns]

Analyzation of Data

In [ ]:
df.head()

Customer ID  Gender  Age  Salary Product ID  Price  Purchased
0            1  Female   49   61000        P01   2000          1
1            2    Male   36   30000        P02   2000          1
2            3  Female   26   81000        P02   3500          1
3            4  Female   32   74000        P01   7000          0
4            5  Female   42   56000        P01   5000          0

**Analyzation Of Data**

In [ ]:
df.count()

Customer ID    1000
Gender         1000
Age            1000
Salary         1000
Product ID     1000
Price          1000
Purchased      1000
dtype: int64

In [ ]:
len(df)

1000

Machine learning models oparate with numerical data therfore any column contain categorical values must me transformed into numeric format. The Gender column has categorical values such has male and female.

One of the method we can utilize to transform categorical values into numerical format is through **One Hot Encoding.**
One Hot Encoding is a way to convert catogorical data into a format that can be understood by machine learning algorithms. It creats a binary vector for each category. In a categorical variable where only one element vector is set to 1 and all other elements set to 0. This technique helps the algorithm to identify and differentiate between different categories without assuming any order or hierarchy among them.
Pandas has get a dummies method. That allows us to perform One Hot Encoding that transform categorical values into numerical values.Lets apply this method to Gender Column.

**Feature Engineering**

In [ ]:
gender_mapping = {'Female': 0, 'Male': 1}

In [ ]:
df['Gender_Numeric'] = df['Gender'].map(gender_mapping)

In [ ]:
print(df[['Gender', 'Gender_Numeric']])

     Gender  Gender_Numeric
0    Female               0
1      Male               1
2    Female               0
3    Female               0
4    Female               0
..      ...             ...
995    Male               1
996    Male               1
997  Female               0
998    Male               1
999  Female               0

[1000 rows x 2 columns]


In [ ]:
df

Customer ID  Gender  Age  Salary Product ID  Price  Purchased  \
0              1  Female   49   61000        P01   2000          1   
1              2    Male   36   30000        P02   2000          1   
2              3  Female   26   81000        P02   3500          1   
3              4  Female   32   74000        P01   7000          0   
4              5  Female   42   56000        P01   5000          0   
..           ...     ...  ...     ...        ...    ...        ...   
995          996    Male   21   73000        P02   5000          1   
996          997    Male   62   54000        P01   5000          0   
997          998  Female   41   20000        P03   2000          0   
998          999    Male   22   29000        P03   5000          0   
999         1000  Female   49   36000        P03   3500          0   

     Gender_Numeric  
0                 0  
1                 1  
2                 0  
3                 0  
4                 0  
..              ...  
995               1  
996               1  
997               0  
998               1  
999               0  

[1000 rows x 8 columns]

In [ ]:
# features or indipendent variables
x = df[['Gender_Numeric','Age','Salary','Price']].to_numpy()

In [ ]:
x

array([[    0,    49, 61000,  2000],
       [    1,    36, 30000,  2000],
       [    0,    26, 81000,  3500],
       ...,
       [    0,    41, 20000,  2000],
       [    1,    22, 29000,  5000],
       [    0,    49, 36000,  3500]])

In [ ]:
# dependent variable
y = df['Purchased'].to_numpy()

In [ ]:
y

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

Splitting data into Training set and Test set. The traing set is used to train the machine learning model and test set to evaluate the performance of the trained model on new unseen data. We use train_test_split function from Scikit learn to split data set into 80 - 20 ratio. The 80% of the data is used for traing and 20% for testing. The exact splitting ratio is dependent on the size of the data set and the cpmplexity of a model and specific requiredments of the problem is being addressed.

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# To ensure ability of our results setting random_state. This way we run same code
# with same random_state will be at the same splitting of data everytime.
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state = 42)

In [ ]:
x_train

array([[    1,    26, 28000,  5000],
       [    1,    54, 21000,  7000],
       [    0,    42, 22000,  5000],
       ...,
       [    0,    59, 91000,  2000],
       [    0,    31, 82000,  2000],
       [    0,    20, 34000,  5000]])

In [ ]:
x_test

array([[     1,     54,  36000,   5000],
       [     0,     54,  60000,   7000],
       [     1,     25,  39000,   2000],
       [     0,     39,  38000,   7000],
       [     1,     28,  37000,   5000],
       [     1,     52,  42000,   2000],
       [     0,     43,  25000,   7000],
       [     0,     40,  22000,   5000],
       [     0,     18,  23000,   3500],
       [     1,     62,  40000,   5000],
       [     1,     53,  66000,   5000],
       [     0,     50,  38000,   7000],
       [     0,     49,  59000,   7000],
       [     0,     56,  97000,   2000],
       [     1,     41,  44000,   3500],
       [     1,     37,  74000,   2000],
       [     0,     51,  23000,   5000],
       [     1,     54,  29000,   2000],
       [     1,     30,  48000,   3500],
       [     1,     56,  87000,   3500],
       [     0,     61,  75000,   7000],
       [     1,     52,  49000,   7000],
       [     0,     38, 100000,   2000],
       [     0,     40,  79000,   5000],
       [     1, 

In [ ]:
y_train

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,

In [ ]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [ ]:
len(x_train)

800

In [ ]:
len(x_test)

200

**Scaling the Features**

Scaling the features machine learning is important because many algorithms used to distance to measures the similarity between different features. If features are not scaled properly features with features with langer numeric ranges condominate the distance measure making difficult for the algorithm to learn from other features.

Scaling helps to ensure that all the features are equally weighted and the algorithm learn all the features eqully.

In [ ]:
from sklearn.preprocessing import StandardScaler

**Standard Scaler** standardizes features by removing the mean and scaling to unit variance. It transforms the data sets into mean of Zero(0) and standard deviation of one(1). It contributes all the featues eqully into the model it prevents featues into larger values from dominating the model.

In [ ]:
scaler = StandardScaler()

In [ ]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [ ]:
x_train

array([[ 1.08347268, -1.09076887, -1.30749141,  0.30934614],
       [ 1.08347268,  0.97668947, -1.60377078,  1.39955279],
       [-0.92295821,  0.0906359 , -1.56144515,  0.30934614],
       ...,
       [-0.92295821,  1.34587846,  1.35902286, -1.32596384],
       [-0.92295821, -0.72157988,  0.97809225, -1.32596384],
       [-0.92295821, -1.53379565, -1.05353767,  0.30934614]])

In [ ]:
x_test

array([[ 0.91370804,  0.84165121, -0.92674628,  0.29135523],
       [-1.0944415 ,  0.84165121,  0.09493083,  1.3460348 ],
       [ 0.91370804, -1.16805526, -0.79903664, -1.29066412],
       [-1.0944415 , -0.19785214, -0.84160652,  1.3460348 ],
       [ 0.91370804, -0.96015459, -0.8841764 ,  0.29135523],
       [ 0.91370804,  0.70305076, -0.671327  , -1.29066412],
       [-1.0944415 ,  0.07934876, -1.39501496,  1.3460348 ],
       [-1.0944415 , -0.12855191, -1.5227246 ,  0.29135523],
       [-1.0944415 , -1.65315683, -1.48015472, -0.49965444],
       [ 0.91370804,  1.396053  , -0.75646676,  0.29135523],
       [ 0.91370804,  0.77235099,  0.35035011,  0.29135523],
       [-1.0944415 ,  0.56445032, -0.84160652,  1.3460348 ],
       [-1.0944415 ,  0.49515009,  0.05236095,  1.3460348 ],
       [-1.0944415 ,  0.98025166,  1.67001638, -1.29066412],
       [ 0.91370804, -0.05925169, -0.58618724, -0.49965444],
       [ 0.91370804, -0.33645258,  0.69090915, -1.29066412],
       [-1.0944415 ,  0.

**Traing The Model**

**KNN Algorithm**
The k-nearest neighbors (KNN) algorithm is a non-parametric, supervised learning method used for both classification and regression tasks.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
k= 5
model = KNeighborsClassifier(n_neighbors=k)

In [ ]:
model.fit(x_train,y_train)

KNeighborsClassifier()

**Testing the Data**

Testing test data set. Use the model to predict the outputs for test set and compare predicted outputs vales with actual values to measure the accuracy of the model.

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [ ]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.765

From here taking a new data while customers buy a product or not using same features. For new data set also performing same feature engineering and scaling steps. Ensure new data set also in a same format and range as data used in training the model.

In [ ]:
new_df = pd.read_csv("https://raw.githubusercontent.com/futurexskill/projects/main/knn-classification/new_customers.csv")

In [ ]:
new_df

Gender  Age  Salary  Product ID  Price
0    Male   24   38652           3   4446
1  Female   47   64727           1   5188
2    Male   46   54648           1   6193
3    Male   31   20018           3   4779
4    Male   58   77731           2   6855
5    Male   28   55478           1   6153
6  Female   48   54211           2   7588
7    Male   31   60076           3   5238
8  Female   42   29290           1   5418
9    Male   50   21445           1   5598

In [ ]:
gender_mapping = {'Female': 0, 'Male': 1}

In [ ]:
new_df['Gender_Numeric'] = df['Gender'].map(gender_mapping)

In [ ]:
print(new_df[['Gender', 'Gender_Numeric']])

   Gender  Gender_Numeric
0    Male               0
1  Female               1
2    Male               0
3    Male               0
4    Male               0
5    Male               1
6  Female               0
7    Male               0
8  Female               0
9    Male               1


In [ ]:
new_df

Gender  Age  Salary  Product ID  Price  Gender_Numeric
0    Male   24   38652           3   4446               0
1  Female   47   64727           1   5188               1
2    Male   46   54648           1   6193               0
3    Male   31   20018           3   4779               0
4    Male   58   77731           2   6855               0
5    Male   28   55478           1   6153               1
6  Female   48   54211           2   7588               0
7    Male   31   60076           3   5238               0
8  Female   42   29290           1   5418               0
9    Male   50   21445           1   5598               1

In [ ]:
x_new = new_df[['Gender_Numeric','Age','Salary','Price']].to_numpy()

In [ ]:
x_new

array([[    0,    24, 38652,  4446],
       [    1,    47, 64727,  5188],
       [    0,    46, 54648,  6193],
       [    0,    31, 20018,  4779],
       [    0,    58, 77731,  6855],
       [    1,    28, 55478,  6153],
       [    0,    48, 54211,  7588],
       [    0,    31, 60076,  5238],
       [    0,    42, 29290,  5418],
       [    1,    50, 21445,  5598]])

In [ ]:
x_new_scaler_2 = scaler.fit_transform(x_new)

In [ ]:
x_new_scaler_2

array([[-0.65465367, -1.54774434, -0.48875298, -1.42543997],
       [ 1.52752523,  0.60971747,  0.93112246, -0.61159228],
       [-0.65465367,  0.51591478,  0.38228547,  0.49072164],
       [-0.65465367, -0.89112553, -1.50343981, -1.06019565],
       [-0.65465367,  1.64154703,  1.63923599,  1.21682294],
       [ 1.52752523, -1.17253359,  0.42748189,  0.44684845],
       [-0.65465367,  0.70352015,  0.35848928,  2.02079916],
       [-0.65465367, -0.89112553,  0.67785916, -0.55675079],
       [-0.65465367,  0.14070403, -0.99854681, -0.35932143],
       [ 1.52752523,  0.89112553, -1.42573465, -0.16189207]])

In [ ]:
y_new_pred = model.predict(x_new_scaler_2)

In [ ]:
y_new_pred

array([1, 1, 1, 0, 0, 1, 0, 1, 0, 0])

These are our new predictions. Customers will buy a product or not. 1 means they will buy a product and 0 means they don't buy a product.